name: Delete workflow

on:
  # これのイベントはデフォルトブランチ(多くの場合、main)上にワークフローファイルがあるときのみ利用できる
  workflow_dispatch:
    inputs:
      workflow:
        description: workflow-id, workflow-name or filename
        required: true
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WORKFLOW: ${{ github.event.inputs.workflow }}

    steps:
      - uses: actions/checkout@v4

      - run: gh workflow view "${WORKFLOW}"
      - name: Execute
        env:
            REPOSITORY: ${{ github.repository }}
        run: |
          gh run list --workflow "${WORKFLOW}" --limit 1000 --json databaseId,status --jq '.[] | select(.status == "completed") | .databaseId' \
            | xargs -n 1 -I {} gh api -X DELETE repos/${REPOSITORY}/actions/runs/{}
