# This is a basic workflow to help you get started with Actions

name: CI-release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: tetsuyainfra/blueprint-github-actions/.github/workflows/blank.yml@main
    # with:
    #   config-path: .github/labeler.yml
    # secrets: inherit

  release_job:
    name: release from artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build hash is
        run: echo ${{ needs.build.outputs.git_hash }}

      - name: Download math result for job 1
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload artifact with renaming
        run: |
          find ./ -type f -exec echo {} \;


      # - name: Upload Release File
      #   run: gh release upload ${{ github.event.ref.tags }}

